application: python-youtube-1192
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico


- url: (.*)/
  static_files: app\1/index.html
  upload: app

- url: /.*
  script: main.app

- url: (.*)
  static_files: app\1
  upload: app
